name: "Bake kernel on dispatch"
run-name: "Build for ${{ github.event.inputs.board || github.event.client_payload.board || 'noble' }} by @${{ github.actor }} (Trigger: ${{ github.event.client_payload.trigger_source || github.event_name }})"

on:
  workflow_dispatch:
    inputs:
      board:
        description: "Board name"
        required: true
        type: string
        default: "orangepi-5-plus"

      artifact_retention_days:
        description: "Artifact retention period in days"
        required: false
        type: number
        default: 1

  repository_dispatch:
    types:
      - event-kernel-bake

env:
  RECIPE_REPO: "diverger/ubuntu-rockchip"
  RECIPE_REF: "diverger"
  RECIPE_PATH: "."
  # Extract values from either workflow_dispatch inputs or repository_dispatch client_payload
  BOARD: ${{ github.event.inputs.board || github.event.client_payload.board || 'noble' }}
  TRIGGER_SOURCE: ${{ github.event.client_payload.trigger_source || github.event_name }}
  ARTIFACT_RETENTION_DAYS: ${{ github.event.inputs.artifact_retention_days || github.event.client_payload.artifact_retention_days || '1' }}

jobs:
  build:
    if: ${{ github.repository_owner == 'diverger' && github.actor == 'diverger' }}
    runs-on: ubuntu-latest
    name: Build kernel

    steps:
      - name: Show trigger source
        run: |
          echo "Workflow triggered by: ${{ env.TRIGGER_SOURCE }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Board: ${{ env.BOARD }}"
          echo "Artifact retention days: ${{ env.ARTIFACT_RETENTION_DAYS }}"

      - name: Show repository dispatch payload (if applicable)
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "Repository dispatch event type: ${{ github.event.action }}"
          echo "Client payload: ${{ toJson(github.event.client_payload) }}"

      - name: Calculate expire date
        id: expire
        run: |
          expire_date=$(date -u -d "+${{ env.ARTIFACT_RETENTION_DAYS }} days" +"%Y-%m-%d")
          echo "Expire date: $expire_date"
          echo "expire_date=$expire_date" >> $GITHUB_OUTPUT
          echo "### Artifact Expire Date: $expire_date" >> $GITHUB_STEP_SUMMARY

      - name: Get more disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.RECIPE_REPO }}
          ref: ${{ env.RECIPE_REF }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: ${{ env.RECIPE_PATH }}
          clean: false
          fetch-depth: 1
          lfs: true

      - name: Run local build
        id: baker_step
        uses: "./.github/actions/kernel-baker"
        with:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          board: ${{ env.BOARD }}
          artifact_retention_days: ${{ env.ARTIFACT_RETENTION_DAYS }}
